### ISSUE TITLE
Python module versions

### ISSUE THREAD

**Issue by richardmnielsen** [MikeGawi/ePiframe#32]
I have just completed 3 separate installations of ePiframe.  Each system is identical and includes a raspberry pi zero w rev 1.1 with the 7.5" waveshare epaper screen.  The automatic installation script operated normally, however each one had an error at a different steps - all with installing python modules via pip3.  In each case, the module was installed manually, then the automatic script rerun.  All completed without errors on the rerun of the install script.

Once the installation was completed, an addition error occurred and is the same on all three systems.  When attempting to run ./ePiframe.py with any argument returns "Illegal instruction"

I wrote a script with only the imports from ePiframe.py and commented each out one by one to determine the issue.  The modules that create this error are:  configmanager, albummanager, randommanager, photomanager and filteringmanager
I believe that this is likely an architecture mismatch with one of the modules that is being installed via pip.  Can you provide a list of versions of each module from a working system?

A similar issue occurred during an initial installation - the current version of raspbian was installed, but the automatic installation script and the manual method failed because several of the required packages are not available for the latest version of raspbian.  I installed the legacy version of raspbian and the installations completed successfully.

**Comment by MikeGawi** [comment]
Yes, sorry for that but apparently numpy with version 1.20+ that is used by new pandas module is causing the issue - wrong architecture used on RasPi. I was also struggling with that for a while (release was planned for yesterday but happened today)but I was able to fix that by: `sudo -H pip3 install --force-reinstall pandas==1.2.0 numpy==1.19.4` as this was the version that was working before update script on not-updated ePiframe. You need to specify numpy version as well because pandas will install the newest realease of it that is not working on Raspberry Pi. Also, the newest pandas version is not working with the previous releases of numpy, so this is the fix by now. 

I've already updated install/update script today but try this and let me know if it's working. 
Sorry for the inconvenience.

**Comment by MikeGawi** [comment]
As for the packages versions that are working on Linux epiframe 5.10.63+ #1496 Wed Dec 1 15:57:05 GMT 2021 armv6l GNU/Linux Raspbian GNU/Linux 10 (buster):
Name: pandas Version: 1.2.0
Name: numpy Version: 1.21.3
Name: Flask Version: 2.0.2
Name: Flask-Login Version: 0.5.0
Name: Flask-WTF Version: 1.0.0
Name: pyTelegramBotAPI Version: 4.1.1
Name: python-dateutil Version: 2.8.2
Name: RPi.GPIO Version: 0.7.0
Name: Pillow Version: 8.4.0
Name: image Version: 1.5.33
Name: configparser Version: 5.2.0
Name: spidev Version: 3.5
Name: WTForms Version: 3.0.0
Name: requests Version: 2.26.0

**Comment by MikeGawi** [comment]
> A similar issue occurred during an initial installation - the current version of raspbian was installed, but the automatic installation script and the manual method failed because several of the required packages are not available for the latest version of raspbian.

I'll check that and will get back to You. Haven't tried with the newest version, thanks for the hint!

**Comment by MikeGawi** [comment]
**I confirm installer/update issues** on the newest version of Raspberry Pi OS, i.e Linux raspberrypi 5.10.63+ #1459 Wed Oct 6 16:40:27 BST 2021 armv6l GNU/Linux - _Raspbian GNU/Linux 11 (bullseye)_. 

I will take a look on that and fix the issues ASAP and let You know it's done.

**Comment by MikeGawi** [comment]
Packages that work on the newest version of Raspberry Pi OS, i.e Linux raspberrypi 5.10.63+ #1459 Wed Oct 6 16:40:27 BST 2021 armv6l GNU/Linux - _Raspbian GNU/Linux 11 (bullseye)_:
Name: requests Version: 2.26.0
Name: Pillow Version: 8.4.0
Name: pyTelegramBotAPI Version: 4.1.1
Name: python-dateutil Version: 2.8.2
Name: configparser Version: 5.2.0
Name: spidev Version: 3.5
Name: image Version: 1.5.33
Name: pandas Version: 1.2.0
Name: numpy Version: 1.20.0
Name: Flask Version: 2.0.2
Name: Flask-WTF Version: 1.0.0
Name: WTForms Version: 3.0.1
Name: Flask-Login Version: 0.5.0

I think I've finally managed to get it working on Raspberry Pi OS Bullseye.
A surprise is a version of numpy that needs to be 1.20.0 and 1.19.4 worked on previous OS. 1.20 works on both.

Anyway, the installer and documentation have been updated. Please check it if possible, let me know the result and close the issue if it's ok now. 
Thanks a lot for help!

**Comment by richardmnielsen** [comment]
Thanks for looking into this right away.  I have force installed pandas 1.2.0 and numpy 1.19.4 and it started working.  The only additional step I had to do to have the config file check out was to install the rrdtool package.  It seems that it was no longer installed after reinstalling pandas and numpy.

I have also tried the new install script on the latest version of raspberry pi os.  It proceeded further than previously, but got hung up on several of the pip module installs. This appears to be a connection issue so I will try it again as soon as I can and post an update.  Below is the output:

**Is root:                      check!

Installing system components
Installing WebP Format:       check!
Installing RAW formats:       check!
Installing RPi.GPIO:          check!
Installing Python 3:          check!
Installing RRDTool:           check!
Installing LibAtlas:          check!
Installing Pip 3:             check!
Installing ImageMagick:       check!

Installing Python components
Installing Requests:          error!
Please try to install sudo -H pip3 install -I requests>=2.26.0 manually and run the script again
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/urllib3/
pi@raspberrypi:~ $ sudo -H pip3 install -I requests>=2.26.0
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/urllib3/
pi@raspberrypi:~ $**


Thanks for all your work on this project, very impressed.

**Comment by MikeGawi** [comment]
Thank You for checking this! 
I'm happy that it worked and as for the connection issue You get, try with not specifying the version, I've found out that sometimes it helps and this error is not related with connectivity.
In fact I've already prepared the fixed installer version to try, as requests module is also installed in the proper version by pandas - let me know if this helps.

>Thanks for all your work on this project, very impressed.

Thank You for Your feedback! It means a lot for me as I'm really happy that my idea and work can make someone happy :smiley:

**Comment by MikeGawi** [comment]
Will be merged and released in [v1.1.0](https://github.com/MikeGawi/ePiframe/releases/tag/v1.1.0)

Tested that a lot on the newest Raspberry Pi OS Bullseye and it seems to be fine - closing. If something like this appear again, please reopen the issue. @richardmnielsen  - Thanks for Your contribution.
