### ISSUE TITLE
HDMI e-paper screens

### ISSUE THREAD

**Issue by richardmnielsen** [MikeGawi/ePiframe#33]
Is it possible to configure ePiframe for use with an HDMI ePaper screen?  I am specifically interested in the 13.3" waveshare screen.  I have two pi zero w boards without headers and the hdmi interface would make a very thin and clean setup.

**Comment by MikeGawi** [comment]
Currently only e-paper displays are supported BUT I need to think about it. Let me do some research and I'll give You feedback what is possible and how long will it takes (I'm also busy with #16). The issues I see by now is how to take over HDMI when Lite OS version is used and how to programatically control the output. 

Please check also https://github.com/mrworf/photoframe as this project is supporting HDMI or SPI/DPI displays and has sensor control, etc.

**Comment by MikeGawi** [comment]
You are probably thinking about this one: 
https://www.waveshare.com/product/displays/e-paper/epaper-1/13.3inch-hdmi-e-paper.htm
It's looking very nice!

OK, I will do the research and let You know.

**Comment by MikeGawi** [comment]
Ok, it's possible even for X and non-X configurations and I think it's a great improvement for ePiframe so starting implementing this.
Thanks!

**Comment by MikeGawi** [comment]
Done, will be released in [version 1.2.0](https://github.com/MikeGawi/ePiframe/releases/tag/v1.2.0)
