### ISSUE TITLE
[Feature Request]: HEIF/HEIC support

### ISSUE THREAD

**Issue by motoxcrazy** [MikeGawi/ePiframe#59]
AFAIK, ePiframe does not currently support HEIF formats. I have a number of these images in my album and the frame seems to get hung up when it reaches one of these photos.

When running `--test` I get the following after "Getting next photo..."

> Traceback (most recent call last):
>   File "/home/pi/ePiframe/./ePiframe.py", line 548, in <module>
>     main()
>   File "/home/pi/ePiframe/./ePiframe.py", line 354, in main
>     + constants.TYPE_TO_EXTENSION[photoman.get_photo_attribute(photo, constants.GOOGLE_PHOTOS_ALBUMS_PHOTO_MIMETYPE_HEADER)]
> KeyError: 'image/heif'

Otherwise, love the frame!!

**Comment by MikeGawi** [comment]
Thanks for the hint! I was not familiar with this format but I'll do some research and try to add support for it. Let me know if You know any other formats beside ones listed [here](https://github.com/MikeGawi/ePiframe/blob/8bf195bf4c7d941ef82eb654301284e56cb062cb/misc/constants.py#L67).

> Otherwise, love the frame!!
Thanks! I'm really happy to hear that!

**Comment by motoxcrazy** [comment]
I added `'image/heif' : ['heic', 'heif']` to the bottom of [your extension list](https://github.com/MikeGawi/ePiframe/blob/8bf195bf4c7d941ef82eb654301284e56cb062cb/misc/constants.py#L67) and it all seems to be working now. Have cycled through a number of HEIC files and they seem to be displaying and not getting caught up.

Not sure what other areas of the project are dependent on this list so haven't issued pull request or anything :)

**Comment by MikeGawi** [comment]
Yep, that should be **it** but strange thing is that it works only on Raspberry Pi ImageMagick version and not on Debian Linux I have (need to check that)... 
Anyway, a pull request would be a very nice contribution (the extension list should not affect anything else), so feel free to create it. Thanks again!

**Comment by motoxcrazy** [comment]
Pull request #60

**Comment by MikeGawi** [comment]
It works only on Raspberry Pi OS version of Imagemagick. To have it elsewhere check:
`convert -list format | grep HEI`

If the version installed supports HEIF/HEIC formats. If not (binaries are needed to be generated) then use [this easy builder](https://github.com/SoftCreatR/imei) and follow the instructions to install it.
