### ISSUE TITLE
Display Sleep

### ISSUE THREAD

**Issue by jakemauer** [MikeGawi/ePiframe#64]
Hi Mike!

I'm using ePiframe with a repurposed HDMI monitor and I'd love to be able to have the monitor go to sleep in the evening and wake up in the morning. While I'm making wishes it would be cool if there was a webhook I could hit to turn it on/off so I could integrate it with my smart home system in Home Assistant. 

Do you know how I would even go about sleeping the display and turning it back on again on a Pi4?
I found this discussion: https://www.reddit.com/r/raspberry_pi/comments/5e860b/how_do_you_get_raspbian_to_turn_off_its_monitor/

which references using `tvservice -o` to turn off the display. tvservice is only available if you're using the fkms driver, not the default kms driver. If I switch to using fkms, the flag `-o` does sleep the display! `-p` wakes it up but the photo picture framebuffer doesn't appear.

**Comment by MikeGawi** [comment]
This is fantastic! I love the idea!
OK, I will do the research, tests and will give you a feedback what is possible. The best would be to control the on/off with the API and/or the service command but I'll find the best way. Also the on/off times will be controlled by the configured frame /on/off times.

Thanks!

**Comment by MikeGawi** [comment]
My findings so far:

- `tvservice` (`-p` and `-o`) works for me on legacy and Fake KMS drivers. Full KMS [will not work](https://forums.raspberrypi.com/viewtopic.php?f=29&t=288234&start=525#p1829997) and is not recommended on Pi0 - maybe I was not searching too deeply but I'm happy it works on the default driver and I'll stick to that (no documentation needed, no specific changes, etc.).
- the `-p` powers up the display but loses "hook" and displays black screen.
- the `-p` powers up the display and `fbset -depth 8` ([dummy fbset to force a refresh](https://forums.raspberrypi.com/viewtopic.php?t=52309#p612540)) updates it (the console appears) so it can display something again.

I still needs some more testing but I will implement that feature soon.

@jakemauer - the `tvservice -o` was not working for you on default driver or I didn't get that right?

**Comment by jakemauer** [comment]
That’s correct. When using the KMS driver it errors out saying tvservice is not available with that driver.

**Comment by MikeGawi** [comment]
Ok, now I know where my confusion came from:
Checked on RPi4 and there the KMS driver (vc4-kms-v3d) is set as default, where on RPi0 a legacy driver is a default. Legacy and FKMS works with `tvservice` and KMS not.

**Comment by MikeGawi** [comment]
I think I've found the best solution that works for every default driver and on every Raspberry Pi (0,3,4):
`vcgencmd display_power 0` and `vcgencmd display_power 1`
For some displays the power off works for few seconds only as hotplug is triggered but that's all about tweaking RPi configuration.

**Please check that solution and let me know**. The more tests performed the better this will work.

**Comment by MikeGawi** [comment]
Implemented and merged to master.

If you want to have the display power off during ePiframe off hours (`start_times` and `stop_times` settings) just use the setting `control_display_power` in _config.cfg_ file or in WebUI: _Settings->Display->Control Display Power_. Obviously that will only work when HDMI display is selected.

As for 

> While I'm making wishes it would be cool if there was a webhook I could hit to turn it on/off so I could integrate it with my smart home system in Home Assistant.

you can use [ePiframe API](https://github.com/MikeGawi/ePiframe/blob/master/docs/API.md#control-display-power) to get status and control the display power. This API command works regardless to the setting mentioned above.

**Comment by jakemauer** [comment]
This is amazing, thank you Mike! I'm waiting to get my display back up and running this weekend but I'll keep you posted.
