### ISSUE TITLE
Losing settings on power loss

### ISSUE THREAD

**Issue by motoxcrazy** [MikeGawi/ePiframe#65]
Not sure if an issue or something up with my rPi, but we live rurally and have had a number of failures recently. When the rPi reboots it seems to retain the Google credentials but not any of the other settings (Randomize, filtered album, telegram bot etc.)
Any ideas on what I should do to troubleshoot? My current fix is to reload the config file after renabling Web interface via ssh.

**Comment by MikeGawi** [comment]
Thanks for the issue! I will check that as that can happen when file is inaccessible or blocked (concurrency?) and then the default settings are loaded. I will get back to you.

**Comment by MikeGawi** [comment]
I think I've found the issue: with WebUI working the config file is frequently checked for changes and during entries load it (preventively) saves it as some conversions/changes could occur. This saving and frequent loading may block the file so it will load just default values.
