### ISSUE TITLE
 How to have the same quality as the original?

### ISSUE THREAD

**Issue by xavierlaffargue** [MikeGawi/ePiframe#66]
I have an HDMI screen, I modified the width/height values ​​in config.cfg but the quality of my photos is not like the original photo (especially concerning the colors)

How to get the best quality?

**Comment by MikeGawi** [comment]
First of all, thank you for raising the issue.

I tried to reproduce the quality/color discrepanties issue on my HDMI frame but I was not able to, so I need to ask you to provide an example photo if possible, both: original and displayed (from ePiframe directory, WebUI or Telegram bot) and a photo of the frame with the wrongly displayed image. I will check it and if encounter the same issue I will fix the converter module.

There are a few things you can check prior to sending files:

- There is an option in settings to limit number of colors: _colors_num_, please check if it's not set
- Play with frame resolution to get the best quality/performance ratio to fit the display
- There are few options to enhance photo quality, i.e. auto-level, brightness, contrast, normalize, auto-gamma. Check if one of these is not corrupting the photo
- Some low quality images can be drastically stretched to fit the display and can cause some visual discrepancies


It also might be a hardware issue:

- Broken Mini-HDMI adapter/cable, display
- Broken HDMI port or plug not fully in (it happened to me with the DVI-HDMI adapter and I thought the display got broken)
and more

**Comment by xavierlaffargue** [comment]
Hi, sorry for the delay but you can close, it was a hdmi issue :)
