### ISSUE TITLE
TypeError with the latest version of Flask installed

### ISSUE THREAD

**Issue by jmurray29** [MikeGawi/ePiframe#70]
Got the following error downloading and running with the latest by install.sh. Fixed by running "sudo pip install -U 'flask<2.2.0'"

> Dec 19 22:23:04 screenpi systemd-timesyncd[2905]: Initial synchronization to time server 178.79.188.22:123 (0.debian.pool.ntp.org).
> Dec 19 22:23:07 screenpi ePiframe_service.py[2865]: Traceback (most recent call last):
> Dec 19 22:23:07 screenpi ePiframe_service.py[2865]:   File "/home/pi/ePiframe/ePiframe_service.py", line 14, in <module>
> Dec 19 22:23:07 screenpi ePiframe_service.py[2865]:     from modules.webuimanager import WebUIManager
> Dec 19 22:23:07 screenpi ePiframe_service.py[2865]:   File "/home/pi/ePiframe/modules/webuimanager.py", line 4, in <module>
> Dec 19 22:23:07 screenpi ePiframe_service.py[2865]:     from flask import (
> Dec 19 22:23:07 screenpi ePiframe_service.py[2865]:   File "/usr/local/lib/python3.9/dist-packages/flask/__init__.py", line 4, in <module>
> Dec 19 22:23:07 screenpi ePiframe_service.py[2865]:     from . import json as json
> Dec 19 22:23:07 screenpi ePiframe_service.py[2865]:   File "/usr/local/lib/python3.9/dist-packages/flask/json/__init__.py", line 8, in <module>
> Dec 19 22:23:07 screenpi ePiframe_service.py[2865]:     from ..globals import current_app
> Dec 19 22:23:07 screenpi ePiframe_service.py[2865]:   File "/usr/local/lib/python3.9/dist-packages/flask/globals.py", line 56, in <module>
> Dec 19 22:23:07 screenpi ePiframe_service.py[2865]:     app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
> Dec 19 22:23:07 screenpi ePiframe_service.py[2865]: TypeError: __init__() got an unexpected keyword argument 'unbound_message'
> Dec 19 22:23:08 screenpi systemd[1]: ePiframe.service: Control process exited, code=exited, status=1/FAILURE

**Comment by MikeGawi** [comment]
Thanks for letting me know, I will check this and try to find a solution.
