### ISSUE TITLE
Support for Pimoroni Inky ePaper displays

### ISSUE THREAD

**Issue by darkrad** [MikeGawi/ePiframe#73]
Is it possible to add support for the Pimoroni Inky ePaper displays in addition to the Waveshare displays? I was hoping to utilise the Inky Impression to create a ePiframe with.
I've come across this project (https://github.com/robweber/omni-epd) that might help with integrating both Inky and Waveshare? But not sure how to go about it =(

**Comment by MikeGawi** [comment]
Thanks for the idea - it is fantastic!
To be honest I am a bit off e-paper displays market as at the time I was creating first versions of ePiframe the Waveshare had almost out-of-the-box ready code with reasonable prices. But life goes on, new stuff appears and these Pimoroni displays are neat!
Also thanks for omni-epd link - it's really helpful.

I will implement support for Pimoroni and I will keep You updated about the progress.

**Comment by MikeGawi** [comment]
Done in version [1.9.0](https://github.com/MikeGawi/ePiframe/releases/tag/v1.9.0). Additionally support for all Waveshare displays (multicolor too) was added.

Unfortunately I couldn't use Omni-EPD as it has an out-dated list of displays so I went a bit further to not have to keep up with the manufacturers in the future: you can choose between Waveshare and Pimoroni but you must specify display code package name and colors schema. The only problem was with differences in implementation among different displays but I think I had this covered.

Also I need to make sure that my 7 color display issues (ghosting, washed colors, etc.) are related with hardware not the code but will implement fix if needed. 

Don't hesitate to report any issue related with Pimoroni display or anything else.

**Comment by chrisjeyre** [comment]
Hi, great project, I managed to get it working over hdmi in the weekend, now my colour pimoroni impression 7.4 has arrived, all connected and test images work, but moving from hdmi to sli does nothing, I just wondered if I had the display setting correct in the web gui? Should these be default, or specific to the screen/vendor?
Thanks in advance

**Comment by MikeGawi** [comment]
Hi, It's not just switching to SPI, you need to set some additional config variables, i.e. obvious one - _epaper_type_ but also _epaper_color_ (the color schema of the display: 7 colors, black&white, etc.) and the _display_ which indicates the class of display to use (should be exact with [this](https://github.com/MikeGawi/ePiframe/blob/master/misc/pimoronidisplay.py#L40)). Then you should test with `--test_display` flag using [command line](https://github.com/MikeGawi/ePiframe/blob/master/INSTALL.md#command-line) and play with the configuration. 

If this will still fail - please create an issue (for which ePiframe version and which Pimoroni display) and I will try to solve it or if you feel good with the code - create a PR with the fix - I really appreciate contributions.
