### ISSUE TITLE
Can't set background color to black

### ISSUE THREAD

**Issue by guaycuru** [MikeGawi/ePiframe#77]
When trying to set:
`background_color=black`
I see this error message when testing the display:
`Error verifying configuration file! background_color configuration entry value should be one of the ['white', 'white', 'photo']`

**Comment by MikeGawi** [comment]
Thanks for creating this issue and pull request! Yep, this is an ugly bug and I'm finishing covering the code with unit tests on the _tests_ branch to prevent having such errors in the future.

**Comment by guaycuru** [comment]
> Thanks for creating this issue and pull request! Yep, this is an ugly bug and I'm finishing covering the code with unit tests on the _tests_ branch to prevent having such errors in the future.

Nah, don't worry, this tool is amazing and you did a great job with it! Thank you very much!
